version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels:
      - "dependencies"
      - "devops"

  - package-ecosystem: gradle
    directory: "/app-api"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: "/app-ui"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    open-pull-requests-limit: 20
    groups:
      ag-grid:
        patterns:
          - "@ag-grid-community/*"
          - "ag-grid-community"
          - "ag-grid-react"
      cypress:
        patterns:
          - "@badeball/cypress-cucumber-preprocessor"
          - "@bahmutov/cypress-esbuild-preprocessor"
          - "cypress"
      emotion:
        patterns:
          - "@emotion/*"
      mui:
        patterns:
          - "@mui/*"
      types:
        patterns:
          - "@types/*"
      react:
        patterns:
          - "react"
          - "react-*"
      babel:
        patterns:
          - "@babel/*"
      jest:
        patterns:
          - "babel-jest"
          - "jest-environment-jsdom"
          - "jest"

