version: '3.8'

services:
  e2e-db:
    image: postgres:latest
    container_name: e2e-postgres
    environment:
      POSTGRES_DB: react-dashboard-e2e
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"