version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.fr
      PGADMIN_DEFAULT_PASSWORD: mypgadminpassword
    volumes:
      - pgadmin-data:/var/lib/postgresql/data

volumes:
  pgadmin-data: