INSERT INTO symbol_values (symbol, name)
VALUES ('AI.XPAR', 'AIR LIQUIDE'), ('RMS.XPAR', 'HERMES'), ('MC.XPAR', 'LVMH'), ('GLE.XPAR', 'SOCIETE GENERALE'),
('KER.XPAR', 'KERING'), ('SU.XPAR', 'SCHNEIDER ELECTRIC'), ('BNP.XPAR', 'BNP PARIBAS'), ('DSY.XPAR', 'DASSAULT SYSTEMES'),
('ML.XPAR', 'MICHELIN'), ('POM.XPAR', 'PLASTIC OMNIUM'), ('AM.XPAR', 'DASSAULT AVIATION'), ('STM.XPAR', 'STMicroelectronics'),
('LR.XPAR', 'LEGRAND'), ('OR.XPAR', 'L''OREAL'), ('RNO.XPAR', 'RENAULT'), ('STLAP.XPAR', 'Stellantis N.V'), ('CS.XPAR', 'AXA'),
('ENGI.XPAR', 'ENGIE'), ('TTE.XPAR', 'TOTALENERGIES'), ('ORA.XPAR', 'ORANGE'), ('ICAD.XPAR', 'ICADE'), ('NXI.XPAR', 'NEXITY'),
('LI.XPAR', 'KLEPIERRE'), ('HO.XPAR', 'THALES')