spring:
  config:
    activate:
      on-profile: e2e
  datasource:
    url: jdbc:postgresql://localhost:5433/react-dashboard-e2e
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
