spring:
  config:
    activate:
      on-profile: e2e
  datasource:
    url: jdbc:postgresql://localhost:5433/react-dashboard-e2e
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  docker:
    compose:
      file: docker/docker-compose-e2e.yml
      stop:
        command: down
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master-e2e.yaml

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

