databaseChangeLog:
  - changeSet:
      id: 20231218-01
      author: admin
      changes:
        - createTable:
            tableName: symbol_values
            columns:
              - column:
                  name: symbol
                  type: VARCHAR(20)
                  constraints:
                    primaryKey: true
              - column:
                  name: name
                  type: VARCHAR(50)
  - changeSet:
      id: 20231219-01
      author: admin
      changes:
        - sqlFile:
            dbms: 'postgresql'
            endDelimiter: \nGO
            splitStatements: true
            path: db/changelog/script/add_symbol_names.sql
            stripComments: true