name: Build Master

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: npm
          cache-dependency-path: app-ui/package-lock.json
      - name: Install dependencies
        run: npm install -D puppeteer karma-chrome-launcher --save-dev @babel/preset-typescript
        working-directory: app-ui
      - name: Build
        run: npm run build
        working-directory: app-ui
      - name: Test
        run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
        working-directory: app-ui

  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: app-ui
          build: npm run build
          start: npm start
