name: Build Master

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Use Node 18.x
        uses: actions/setup-node@v5
        with:
          node-version: "18.x"
          cache: npm
          cache-dependency-path: app-ui/package-lock.json
      - name: Install dependencies
        run: npm install -D puppeteer karma-chrome-launcher --save-dev @babel/preset-typescript
        working-directory: app-ui
      - name: Build
        run: npm run build
        working-directory: app-ui
      - name: Test
        run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI
        working-directory: app-ui

  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "adopt"
      - name: Start Backend server
        run: ./gradlew bootRun --args='--spring.profiles.active=e2e' &
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: app-ui
          build: npm run build
          start: npm start
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: /home/runner/work/StockMarketDashboard/StockMarketDashboard/app-ui/cypress/screenshots
      - name: Stop Backend server
        run: curl -X POST http://localhost:8080/actuator/shutdown
        if: always()

  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install typescript
        working-directory: ./app-ui
        run: npm i typescript
      - name: Run Docker-compose
        working-directory: ./docker
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 5
          docker compose -f docker-compose.yml ps
      - name: Check UI
        run: curl http://localhost:3000
      - name: Stop and remove containers
        working-directory: ./docker
        run: docker compose -f docker-compose.yml down
        if: always()
